#!/usr/bin/env bash
# =============================================================================
# ssm-env.sh — Fetch secrets from SSM and write .env.production.local
# =============================================================================
# Usage (on the server during deploy):
#   source scripts/ssm-env.sh          # exports vars into current shell
#   scripts/ssm-env.sh > .env.production.local  # writes env file
# =============================================================================

set -euo pipefail

REGION="${AWS_REGION:-us-west-2}"
PREFIX="/redeye/dashboard"

echo "# Generated by ssm-env.sh — do not edit manually" >&2
echo "# Fetching secrets from SSM $PREFIX ..." >&2

aws ssm get-parameters-by-path \
  --region "$REGION" \
  --path "$PREFIX" \
  --with-decryption \
  --recursive \
  --query "Parameters[*].[Name,Value]" \
  --output text \
  --no-cli-pager | while IFS=$'\t' read -r NAME VALUE; do
    KEY="${NAME##*/}"   # strip the /redeye/dashboard/ prefix
    echo "${KEY}=${VALUE}"
done

echo "" >&2
echo "✅ SSM fetch complete." >&2
