name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: RedEyeDevelopment/.github/.github/workflows/deploy.yml@main
    with:
      app-name: 'dashboard-redeye'
      working-directory: '/var/www/redeye-dashboard'
    secrets:
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
